# Generated by Django 3.0.4 on 2020-04-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_mysite.order_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_toppings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('small_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Pizza')),
            ],
            bases=('mysite.pizza',),
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Pizza')),
            ],
            bases=('mysite.pizza',),
        ),
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('order_num', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=30)),
                ('finished', models.BooleanField(default=False)),
                ('orders', models.ManyToManyField(to='mysite.Order')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('time', models.TimeField()),
                ('size_small', models.BooleanField(default=False)),
                ('extra', models.ManyToManyField(blank=True, to='mysite.SubExtra')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Sub')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mysite.order',),
        ),
        migrations.CreateModel(
            name='SaladOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('time', models.TimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Salad')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mysite.order',),
        ),
        migrations.CreateModel(
            name='PlatterOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('time', models.TimeField()),
                ('size_small', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Platter')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mysite.order',),
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('time', models.TimeField()),
                ('size_small', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Pizza')),
                ('toppings', models.ManyToManyField(to='mysite.PizzaTopping')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mysite.order',),
        ),
        migrations.CreateModel(
            name='PastaOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('time', models.TimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Pasta')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mysite.order',),
        ),
    ]
