# Generated by Django 3.0.4 on 2020-04-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200410_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size_small',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub',
            name='size_small',
            field=models.BooleanField(default=False),
        ),
    ]
