# Generated by Django 3.0.4 on 2020-04-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200410_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='large_price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='small_price',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='large_price',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='small_price',
        ),
    ]
