# Generated by Django 3.0.4 on 2020-04-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200410_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzatopping',
            name='large_price',
        ),
        migrations.RemoveField(
            model_name='pizzatopping',
            name='small_price',
        ),
    ]
