# Generated by Django 3.0.4 on 2020-04-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200411_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='mysite.PizzaTopping'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='extra',
            field=models.ManyToManyField(blank=True, to='mysite.SubExtra'),
        ),
    ]
