# Generated by Django 3.0.4 on 2020-04-12 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200411_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Pizza')),
            ],
            bases=('mysite.pizza',),
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Pizza')),
            ],
            bases=('mysite.pizza',),
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size_small',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='platter',
            name='order',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size_small',
        ),
        migrations.AddField(
            model_name='pizza',
            name='big_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='large_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('size_small', models.BooleanField(default=False)),
                ('extra', models.ManyToManyField(blank=True, null=True, to='mysite.SubExtra')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Sub')),
            ],
            bases=('mysite.order',),
        ),
        migrations.CreateModel(
            name='SaladOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Salad')),
            ],
            bases=('mysite.order',),
        ),
        migrations.CreateModel(
            name='PlatterOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Platter')),
            ],
            bases=('mysite.order',),
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('size_small', models.BooleanField(default=False)),
                ('cheese', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Pizza')),
                ('toppings', models.ManyToManyField(to='mysite.PizzaTopping')),
            ],
            bases=('mysite.order',),
        ),
        migrations.CreateModel(
            name='PastaOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.Order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Pasta')),
            ],
            bases=('mysite.order',),
        ),
    ]
