# Generated by Django 3.0.4 on 2020-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200412_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platter',
            name='price',
        ),
        migrations.AddField(
            model_name='platter',
            name='big_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platter',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platterorder',
            name='size_small',
            field=models.BooleanField(default=False),
        ),
    ]
