# Generated by Django 3.0.4 on 2020-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20200412_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='extra',
            field=models.ManyToManyField(blank=True, to='mysite.SubExtra'),
        ),
    ]
