# Generated by Django 3.0.4 on 2020-04-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200412_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platter',
            old_name='big_price',
            new_name='large_price',
        ),
    ]
