# Generated by Django 3.0.4 on 2020-04-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20200412_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='big_price',
            new_name='large_price',
        ),
    ]
